import assert from 'node:assert/strict';
import test from 'node:test';
import {createIdentity,deviceId,randomToken,createInvitation,parseInvitation,pairingProof,verifyPairingProof,createSecureChannel,encodeBytes,decodeBytes} from '../src/peerSyncCrypto.ts';
async function peers(){const [alice,bob]=await Promise.all([createIdentity(),createIdentity()]);const aNonce=randomToken(),bNonce=randomToken();const [send,receive]=await Promise.all([createSecureChannel(alice,bob.publicKey,aNonce,bNonce),createSecureChannel(bob,alice.publicKey,bNonce,aNonce)]);return {alice,bob,aNonce,bNonce,send,receive};}
test('unique stable PeerJS-safe identities retain nonextractable private keys',async()=>{const [alice,bob]=await Promise.all([createIdentity(),createIdentity()]);assert.match(alice.id,/^rppl-[a-f0-9]{64}$/);assert.equal(await deviceId(alice.publicKey),alice.id);assert.notEqual(alice.id,bob.id);assert.equal(alice.privateKey.extractable,false);await assert.rejects(crypto.subtle.exportKey('jwk',alice.privateKey));assert.equal(typeof(await createSecureChannel(structuredClone(alice),bob.publicKey,randomToken(),randomToken())).seal,'function');});
test('invites accept QR fragments and reject expiry, false identities and malformed secrets',async()=>{const a=await createIdentity(),now=Date.now(),encoded=createInvitation(a,now),invite=await parseInvitation(`https://example.test/#pair=${encoded}`,now);assert.equal(invite.publicKey,a.publicKey);assert.equal(decodeBytes(invite.secret,32).length,32);await assert.rejects(parseInvitation(encoded,now+300000),/expired/);const enc=v=>encodeBytes(new TextEncoder().encode(JSON.stringify(v)));await assert.rejects(parseInvitation(enc({...invite,id:'rppl-impostor'}),now),/Invalid/);await assert.rejects(parseInvitation(enc({...invite,secret:'short'}),now));await assert.rejects(parseInvitation(enc({...invite,expiresAt:now+900000}),now),/expired/);await assert.rejects(parseInvitation('garbage',now));});
test('pairing proofs authenticate the exact handshake and secret',async()=>{const secret=randomToken(),text=JSON.stringify(['device-a','nonce-a','device-b']),proof=await pairingProof(secret,text);assert.equal(await verifyPairingProof(secret,text,proof),true);assert.equal(await verifyPairingProof(randomToken(),text,proof),false);assert.equal(await verifyPairingProof(secret,text.replace('device-b','attacker'),proof),false);assert.equal(await verifyPairingProof(secret,text,'not-a-proof'),false);});
test('ciphertext hides workout data and rejects unauthorized private keys',async()=>{const {alice,aNonce,bNonce,send,receive}=await peers(),outsider=await createIdentity(),impostor=await createSecureChannel(outsider,alice.publicKey,bNonce,aNonce),frame=await send.seal({workoutId:'private-workout',reps:8});assert.equal(JSON.stringify(frame).includes('private-workout'),false);await assert.rejects(impostor.open(frame));assert.deepEqual(await receive.open(frame),{workoutId:'private-workout',reps:8});assert.deepEqual(await send.open(await receive.seal({received:true})),{received:true});});
test('tampering, sequence changes, reflection and replay are rejected',async()=>{const {send,receive}=await peers(),frame=await send.seal({reps:8}),altered=decodeBytes(frame.data);altered[0]^=1;await assert.rejects(receive.open({...frame,data:encodeBytes(altered)}));await assert.rejects(receive.open({...frame,seq:1}),/out-of-order/);await assert.rejects(send.open(frame));assert.deepEqual(await receive.open(frame),{reps:8});await assert.rejects(receive.open(frame),/Replayed/);});
test('parallel delivery accepts a frame at most once',async()=>{const {send,receive}=await peers(),frame=await send.seal({reps:8}),results=await Promise.allSettled([receive.open(frame),receive.open(frame)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.filter(r=>r.status==='rejected').length,1);});
test('new sessions reject old connection frames and oversized payloads',async()=>{const {alice,bob,send}=await peers(),frame=await send.seal({reps:8}),fresh=await createSecureChannel(bob,alice.publicKey,randomToken(),randomToken());await assert.rejects(fresh.open(frame));await assert.rejects(send.seal({oversized:'x'.repeat(40000)}),/too large/);await assert.rejects(createSecureChannel(alice,alice.publicKey,randomToken(),randomToken()),/itself/);});
