import assert from 'node:assert/strict';
import test from 'node:test';
import * as A from '@automerge/automerge';
import {createSyncDoc,emptySyncSnapshot,listSyncConflicts,projectSyncDoc,resolveSyncConflict,updateSyncDoc,validateSyncDoc} from '../src/peerSyncModel.ts';
const exercise='Barbell bench press';
const key=(...parts)=>JSON.stringify(parts);
const merge=(a,b)=>A.merge(A.clone(a),b);
function workout(id='workout-1',date='2026-09-01') {return {id,workout:'push',startedAt:`${date}T05:00:00.000Z`,endedAt:`${date}T06:00:00.000Z`,bodyweight:'65',note:'Original note',exercises:[{name:exercise,priority:'must',sets:[{load:'55',reps:'8'},{load:'55',reps:'7'}]}],sync:{status:'unsynced'}};}
function snapshot(...completed){const s=emptySyncSnapshot();s.completed=completed;for(const w of completed)for(const e of w.exercises)(s.history[e.name]??=[]).push({id:`${w.id}:${e.name}`,savedAt:w.endedAt,sets:structuredClone(e.sets)});return s;}
function edit(doc,change){const before=projectSyncDoc(doc),after=structuredClone(before);change(after);return updateSyncDoc(doc,before,after);}
function choose(doc,k,value){const c=listSyncConflicts(doc).find(c=>c.key===k);assert.ok(c,`Missing conflict ${k}`);const option=c.options.find(o=>o.value===value);assert.ok(option,`Missing option ${value}`);return resolveSyncConflict(doc,k,option.id);}
function active(){const s=emptySyncSnapshot();s.activeWorkout={id:'active-1',workout:'push',startedAt:'2026-09-01T05:00:00.000Z'};s.drafts={[exercise]:[{load:'55',reps:'8'}]};s.checkpoints={[exercise]:{workoutId:'active-1',fingerprint:JSON.stringify(s.drafts[exercise])}};s.bodyweight='65';s.sessionNote='Started on phone';return s;}
test('identical independent imports merge once, seed stable set IDs, and round-trip history',()=>{
const s=snapshot(workout()),m=merge(createSyncDoc(s),createSyncDoc(structuredClone(s))),p=projectSyncDoc(m);
assert.equal(p.completed.length,1);assert.equal(p.history[exercise].length,1);assert.ok(p.completed[0].exercises[0].sets.every(s=>s.id));assert.deepEqual(listSyncConflicts(m),[]);assert.deepEqual(projectSyncDoc(A.load(A.save(m))),p);
});
test('equivalent receipt key ordering does not create conflicts',()=>{const a=snapshot(workout()),b=structuredClone(a);a.completed[0].sync={status:'synced',projectId:3,autumnSessionId:42};b.completed[0].sync={autumnSessionId:42,status:'synced',projectId:3};assert.deepEqual(listSyncConflicts(merge(createSyncDoc(a),createSyncDoc(b))),[]);});
test('preexisting histories form a union and empty browser does not override next',()=>{const a=snapshot(workout('a')),b=snapshot(workout('b','2026-09-02'));a.next=b.next='pull';const m=merge(merge(createSyncDoc(a),createSyncDoc(b)),createSyncDoc()),p=projectSyncDoc(m);assert.equal(p.completed.length,2);assert.equal(p.history[exercise].length,2);assert.equal(p.next,'pull');assert.deepEqual(listSyncConflicts(m),[]);});
test('independent note and set edits both survive in workout and derived history',()=>{const base=createSyncDoc(snapshot(workout()));const a=edit(A.clone(base),s=>{s.completed[0].note='Laptop note';}),b=edit(A.clone(base),s=>{s.completed[0].exercises[0].sets[0].reps='10';}),m=merge(a,b),p=projectSyncDoc(m);assert.equal(p.completed[0].note,'Laptop note');assert.equal(p.completed[0].exercises[0].sets[0].reps,'10');assert.equal(p.history[exercise][0].sets[0].reps,'10');assert.deepEqual(listSyncConflicts(m),[]);});
test('same-field edits retain both values, explicit resolution and later correction converge',()=>{const base=createSyncDoc(snapshot(workout()));const a=edit(A.clone(base),s=>{s.completed[0].exercises[0].sets[0].reps='9';}),b=edit(A.clone(base),s=>{s.completed[0].exercises[0].sets[0].reps='10';});let m=merge(a,b);const c=listSyncConflicts(m);assert.equal(c.length,1);assert.match(c[0].label,/Barbell bench press.*set 1.*reps/);assert.deepEqual(c[0].options.map(o=>o.value).sort(),['10','9']);m=choose(m,c[0].key,'9');assert.equal(projectSyncDoc(m).completed[0].exercises[0].sets[0].reps,'9');assert.deepEqual(listSyncConflicts(m),[]);m=edit(m,s=>{s.completed[0].exercises[0].sets[0].reps='12';});assert.equal(projectSyncDoc(m).completed[0].exercises[0].sets[0].reps,'12');assert.deepEqual(listSyncConflicts(m),[]);});
test('repeated delivery and committed crash journal are idempotent without resolving conflicts',()=>{const base=createSyncDoc(snapshot(workout())),before=projectSyncDoc(base),after=structuredClone(before);after.completed[0].note='Journal edit';const changed=updateSyncDoc(A.clone(base),before,after);assert.deepEqual(A.getHeads(updateSyncDoc(changed,before,after)),A.getHeads(changed));const other=edit(A.clone(base),s=>{s.completed[0].note='Other edit';});const m=merge(changed,other),winner=projectSyncDoc(m),replay=updateSyncDoc(m,before,winner);assert.deepEqual(A.getHeads(replay),A.getHeads(m));assert.equal(listSyncConflicts(replay).length,1);assert.deepEqual(projectSyncDoc(merge(replay,changed)),winner);});
test('stale browser cannot resurrect deleted workout or derived lifts',()=>{const base=createSyncDoc(snapshot(workout())),d=edit(A.clone(base),s=>{s.completed=[];s.history={};}),m=merge(d,base);assert.deepEqual(projectSyncDoc(m).completed,[]);assert.deepEqual(projectSyncDoc(m).history,{});assert.deepEqual(listSyncConflicts(m),[]);});
test('concurrent delete and edit retain one actionable conflict that restores all sets',()=>{const base=createSyncDoc(snapshot(workout())),d=edit(A.clone(base),s=>{s.completed=[];s.history={};}),e=edit(A.clone(base),s=>{s.completed[0].exercises[0].sets[0].reps='11';});let m=merge(d,e);assert.deepEqual(projectSyncDoc(m).completed,[]);assert.equal(listSyncConflicts(m).length,1);m=choose(m,key('workout','workout-1','alive'),'Keep record');assert.equal(projectSyncDoc(m).completed[0].exercises[0].sets[0].reps,'11');assert.equal(projectSyncDoc(m).history[exercise].length,1);assert.deepEqual(listSyncConflicts(m),[]);});
test('concurrent independent added sets retain their UUIDs',()=>{const base=createSyncDoc(snapshot(workout())),a=edit(A.clone(base),s=>{s.completed[0].exercises[0].sets.push({id:'phone-set',load:'55',reps:'5'});}),b=edit(A.clone(base),s=>{s.completed[0].exercises[0].sets.push({id:'laptop-set',load:'50',reps:'9'});}),m=merge(a,b),sets=projectSyncDoc(m).completed[0].exercises[0].sets;assert.equal(sets.length,4);assert.equal(new Set(sets.map(s=>s.id)).size,4);assert.deepEqual(listSyncConflicts(m),[]);});
test('draft edits invalidate old checkpoints and retain independent notes',()=>{const base=createSyncDoc(active());assert.ok(projectSyncDoc(base).checkpoints[exercise]);const a=edit(A.clone(base),s=>{s.drafts[exercise][0].reps='9';}),b=edit(A.clone(base),s=>{s.sessionNote='Laptop note';}),m=merge(a,b),p=projectSyncDoc(m);assert.equal(p.drafts[exercise][0].reps,'9');assert.equal(p.sessionNote,'Laptop note');assert.equal(p.checkpoints[exercise],undefined);assert.deepEqual(listSyncConflicts(m),[]);});
test('distinct active workouts keep their drafts separate',()=>{const a=active(),b=active();b.activeWorkout.id='active-2';b.drafts[exercise][0].reps='12';b.checkpoints={};const m=merge(createSyncDoc(a),createSyncDoc(b));for(const id of ['active-1','active-2']){const selected=choose(A.clone(m),key('state','activeId'),id);assert.equal(projectSyncDoc(selected).drafts[exercise][0].reps,id==='active-1'?'8':'12');}});
test('finish versus offline draft edit can reopen and correct the same workout UUID',()=>{const base=createSyncDoc(active()),finished=edit(A.clone(base),s=>{const w=workout('active-1');w.exercises[0].sets=s.drafts[exercise];s.completed=[w];s.history={};s.activeWorkout=null;s.drafts={};s.checkpoints={};s.next='pull';}),edited=edit(A.clone(base),s=>{s.drafts[exercise][0].reps='11';});let m=merge(finished,edited);assert.equal(projectSyncDoc(m).completed.length,1);assert.equal(projectSyncDoc(m).activeWorkout,null);m=choose(m,key('active','active-1','alive'),'Keep record');m=choose(m,key('state','activeId'),'active-1');let p=projectSyncDoc(m);assert.equal(p.activeWorkout.id,'active-1');assert.equal(p.drafts[exercise][0].reps,'11');m=edit(m,s=>{s.completed[0].exercises[0].sets=s.drafts[exercise];s.activeWorkout=null;s.drafts={};s.checkpoints={};});p=projectSyncDoc(m);assert.equal(p.completed.length,1);assert.equal(p.completed[0].exercises[0].sets[0].reps,'11');assert.equal(p.activeWorkout,null);assert.deepEqual(listSyncConflicts(m),[]);});
test('grouped legacy workout does not duplicate original lift',()=>{const w=workout('legacy-2026-09-01:push');w.sync={status:'legacy'};const s=snapshot(w);s.history[exercise][0].id='old-lift';assert.equal(projectSyncDoc(createSyncDoc(s)).history[exercise].length,1);});
test('remote validation rejects unknown fields, credentials, mutable text and invalid hidden conflicts',()=>{const base=createSyncDoc(snapshot(workout()));const unknown=A.change(A.clone(base),d=>{d.values[key('credentials','token')]=new A.ImmutableString('"secret"');});assert.throws(()=>validateSyncDoc(unknown),/unsupported field/);const credential=A.change(A.clone(base),d=>{d.values[key('workout','workout-1','sync')]=new A.ImmutableString(JSON.stringify(JSON.stringify({status:'synced',token:'secret'})));});assert.throws(()=>validateSyncDoc(credential),/credentials/);const mutable=A.change(A.clone(base),d=>{d.values[key('state','next')]='"pull"';});assert.throws(()=>validateSyncDoc(mutable),/non-scalar/);const setId=projectSyncDoc(base).completed[0].exercises[0].sets[0].id,invalid=A.change(A.clone(base),d=>{d.values[key('set','workout','workout-1',exercise,setId,'reps')]=new A.ImmutableString('"-3"');}),valid=edit(A.clone(base),s=>{s.completed[0].exercises[0].sets[0].reps='12';});assert.throws(()=>validateSyncDoc(merge(invalid,valid)),/completed set reps/);});

test('legacy lift aliases survive corrections after meeting a lift-only browser',()=>{const saved=workout('legacy-2026-09-01:push');saved.sync={status:'legacy'};const a=snapshot(saved);a.history[exercise][0].id='old-lift-session';const b={...emptySyncSnapshot(),history:structuredClone(a.history)};let doc=merge(createSyncDoc(a),createSyncDoc(b));assert.equal(projectSyncDoc(doc).history[exercise].length,1);doc=edit(doc,s=>{s.completed[0].exercises[0].sets[0].reps='12';});assert.equal(projectSyncDoc(doc).history[exercise].length,1);assert.equal(projectSyncDoc(doc).history[exercise][0].sets[0].reps,'12');doc=edit(doc,s=>{s.completed=[];s.history={};});assert.deepEqual(projectSyncDoc(doc).history,{});});
