import { useEffect, useRef, useState, type FormEvent } from 'react';
import type { CompletedWorkout } from './sessionModel';
import type { TrainingPhase } from './planModel';
import { localDay, weightMilestones, type BodyProgressData, type WeightReading } from './bodyProgressModel';
import { getProgressPhotos, PHOTO_PROGRESS_CHANGE_EVENT } from './photoStorage';
import { phaseProgress, suggestedWeightMilestones } from './progressOverviewModel';

const number=(value:number)=>value.toLocaleString(undefined,{maximumFractionDigits:2});
const date=(value:string)=>new Date(`${value.slice(0,10)}T12:00:00`).toLocaleDateString(undefined,{day:'numeric',month:'short'});
const signed=(value:number)=>`${value>0?'+':''}${number(value)}`;

export function GoalOverview({data,readings,ready,busy,onSave,onWeight,onMeasure,onPhotos}:{data:BodyProgressData;readings:WeightReading[];ready:boolean;busy:boolean;onSave:(data:BodyProgressData,message:string)=>Promise<boolean>;onWeight:()=>void;onMeasure:()=>void;onPhotos?:()=>void}) {
  const goal=data.goal.targets.at(-1), latest=readings.at(-1), milestones=weightMilestones(readings,data.goal);
  const [editing,setEditing]=useState(false), [target,setTarget]=useState(''), [steps,setSteps]=useState<number[]>([]);
  const field=useRef<HTMLInputElement>(null);
  useEffect(()=>{if(editing)field.current?.focus();},[editing]);
  const targetValue=Number(target.trim().replace(',','.'));
  const options=[...new Set([...suggestedWeightMilestones(latest?.value,targetValue),...steps.filter(value=>value<targetValue)])].sort((a,b)=>a-b);
  function edit(){setTarget(goal===undefined?'':String(goal));setSteps(data.goal.targets.filter(value=>value!==goal));setEditing(true);}
  async function save(event:FormEvent){event.preventDefault();if(await onSave({...data,goal:{...data.goal,targets:[...new Set([...steps.filter(value=>value<targetValue),targetValue])],minimumReadings:3,updatedAt:new Date().toISOString()}},'Goal saved. Milestones update automatically.'))setEditing(false);}
  return <section className="progress-journey" aria-label="Your weight goal"><div className="journey-heading"><div><p className="journey-context">{goal!==undefined?'Your weight goal':'A little more context with every check-in'}</p><h3>{goal!==undefined?<>Building toward <span>{number(goal)} kg</span></>:'Your progress, over time.'}</h3></div><button type="button" className="quiet-action" disabled={!ready||busy} onClick={edit}>{goal===undefined?'Set a goal':'Edit goal'}</button></div>
    <div className="journey-reading"><div><strong>{latest?number(latest.value):'—'}<small>kg</small></strong><span>{latest?`Latest reading · ${date(latest.date)}`:'Your first weigh-in starts the record'}</span></div><p>{goal!==undefined&&latest?(latest.value<goal?<><b>{number(goal-latest.value)} kg</b> to your goal</>:<>Goal weight reached.<br/>{milestones.at(-1)?.sustained?'Your trend has sustained it, too.':'More readings will show whether it holds.'}</>):'Choose a goal, then let your readings tell the story.'}</p></div>
    <div className="progress-checkin-actions"><button type="button" className="body-primary" disabled={!ready||busy} onClick={onWeight}>Log weigh-in</button><button type="button" disabled={!ready||busy} onClick={onMeasure}>Add measurements</button><button type="button" onClick={onPhotos}>Add photos</button></div>
    {editing&&<form className="body-entry-form goal-editor" onSubmit={event=>void save(event)}><label>Goal weight (kg)<input ref={field} required inputMode="decimal" value={target} placeholder="e.g. 70" onChange={event=>setTarget(event.target.value)}/></label>{options.length>0&&<fieldset className="goal-suggestions"><legend>Optional milestones along the way</legend><p>Choose any you’d like to celebrate.</p><div>{options.map(value=><button type="button" key={value} aria-pressed={steps.includes(value)} onClick={()=>setSteps(previous=>previous.includes(value)?previous.filter(item=>item!==value):[...previous,value])}>{number(value)} kg{steps.includes(value)?' ✓':''}</button>)}</div></fieldset>}<div className="body-actions"><button type="submit" className="body-primary" disabled={busy}>Save goal</button><button type="button" disabled={busy} onClick={()=>setEditing(false)}>Cancel</button></div></form>}
    {milestones.length>0&&<div className="journey-milestones"><ol>{milestones.map(item=><li key={item.target} data-achieved={item.sustained?'sustained':item.firstReached?'reached':'pending'}><span className="milestone-mark" aria-hidden="true">{item.sustained?'✓':item.firstReached?'•':'○'}</span><strong>{number(item.target)} kg</strong><span>{item.sustained?`Sustained · ${date(item.sustained)}`:item.firstReached?`First reached · ${date(item.firstReached)}`:'Ahead'}</span></li>)}</ol><details><summary>How milestones work</summary><p>First reached marks a daily reading at the target. Sustained means your 7-day average reaches it with at least {data.goal.minimumReadings??3} separate recorded days. You can miss a day; no weight is filled in for you.</p></details></div>}
  </section>;
}

function PhotoCheckIn({onOpen}:{onOpen?:()=>void}) {
  const [state,setState]=useState<{count:number;photos:Array<{url:string;date:string;view:string}>;error:string}>({count:0,photos:[],error:''});
  useEffect(()=>{let active=true;let request=0;let urls:string[]=[];const refresh=async()=>{const id=++request;try{const all=await getProgressPhotos();if(!active||id!==request)return;const view=['front','side','back'].find(view=>all.some(photo=>photo.view===view));const same=all.filter(photo=>photo.view===view).sort((a,b)=>a.date.localeCompare(b.date)||a.createdAt.localeCompare(b.createdAt));const selected=same.length>1?[same[0],same.at(-1)!]:same;const photos=selected.map(photo=>({url:URL.createObjectURL(photo.thumbnail),date:photo.date,view:photo.view}));urls.forEach(url=>URL.revokeObjectURL(url));urls=photos.map(photo=>photo.url);setState({count:all.length,photos,error:''});}catch{if(active&&id===request)setState({count:0,photos:[],error:'Photo storage is unavailable. Open Photos to retry.'});}};void refresh();window.addEventListener(PHOTO_PROGRESS_CHANGE_EVENT,refresh);return()=>{active=false;window.removeEventListener(PHOTO_PROGRESS_CHANGE_EVENT,refresh);urls.forEach(url=>URL.revokeObjectURL(url));};},[]);
  return <section className="overview-photos" aria-label="Photo check-ins"><div className="overview-section-title"><h3>Photo check-ins</h3><span>{state.count} saved</span></div>{state.error?<p>{state.error}</p>:state.photos.length?<div className="overview-photo-pair">{state.photos.map((photo,index)=><figure key={photo.url}><img src={photo.url} alt={`${photo.view} check-in from ${date(photo.date)}`}/><figcaption>{index===0&&state.photos.length>1?'First':'Latest'} · {date(photo.date)}</figcaption></figure>)}</div>:<div className="overview-photo-empty"><svg viewBox="0 0 160 90" aria-hidden="true"><rect x="30" y="10" width="100" height="68" rx="8"/><circle cx="80" cy="35" r="10"/><path d="M60 69c0-24 40-24 40 0M40 22h12M108 66h12"/></svg><p>A visual record alongside the numbers.</p><small>Same view, similar light, your own pace.</small></div>}<button type="button" onClick={onOpen}>{state.count?'Compare check-ins':'Add your first photo'}</button><small className="overview-private-note">Saved locally · optional cloud backup.</small></section>;
}

export function ProgressContext({data,readings,sessions,phase,phases,onPhotos,onPlan}:{data:BodyProgressData;readings:WeightReading[];sessions:CompletedWorkout[];phase?:TrainingPhase;phases?:TrainingPhase[];onPhotos?:()=>void;onPlan?:()=>void}) {
  const [selectedId,setSelectedId]=useState('');
  const selected=phases?.find(item=>item.id===selectedId)??phase;
  const end=selected?phases?.filter(item=>item.startedAt>selected.startedAt).sort((a,b)=>a.startedAt.localeCompare(b.startedAt))[0]?.startedAt:undefined;
  const result=selected?phaseProgress(selected,sessions,readings,data.measurements,end):null;
  return <div className="progress-context-grid"><section className="overview-phase" aria-label="Training phase progress"><div className="overview-section-title"><h3>{selected&&selected.id!==phase?.id?'Earlier phase':'Your training phase'}</h3>{onPlan&&<button className="quiet-action" type="button" onClick={onPlan}>View plan</button>}</div>{selected&&result?<><h4>{selected.name}</h4><p className="phase-progress-context">{selected.programName??'Push / Pull / Legs'} · since {date(localDay(new Date(result.startedAt)))}</p>{selected.purpose&&<p>{selected.purpose}</p>}<div className="phase-progress-stats"><div><strong>{result.workouts}</strong><span>completed workouts</span></div><div><strong className={result.weight ? undefined : 'phase-weight-empty'}>{result.weight?`${signed(result.weight.latest-result.weight.first)} kg`:'—'}</strong><span>{result.weight?`weight change · ${result.weight.count} readings`:`Weight change needs two weigh-ins since ${date(localDay(new Date(result.startedAt)))}`}</span></div></div>{result.lifts.length>0&&<div className="phase-lift-changes"><h5>Top working sets · first → latest</h5>{result.lifts.map(lift=><p key={lift.name}><span>{lift.name}</span><strong>{number(lift.first.load)} × {lift.first.reps} → {number(lift.latest.load)} × {lift.latest.reps}</strong></p>)}<small>Loads in kg as recorded; reps shown for context.</small></div>}{result.measurements.length>0&&<p className="phase-tape-changes">{result.measurements.map(item=>`${item.key} ${signed(item.latest-item.first)} cm`).join(' · ')}</p>}{!result.workouts&&<p className="overview-empty-hint">Completed workouts will build this phase’s training record.</p>}{(phases?.length??0)>1&&<label className="phase-history-select">Explore a phase<select value={selected.id} onChange={event=>setSelectedId(event.target.value)}>{[...(phases??[])].reverse().map(item=><option key={item.id} value={item.id}>{item.name}{item.id===phase?.id?' · current':''}</option>)}</select></label>}</>:<p>Start a training phase to see its progress here.</p>}</section><PhotoCheckIn onOpen={onPhotos}/></div>;
}
